### PR TITLE
Accept generator option "package_prefix"

### PR DESCRIPTION
**Pull request by ericklaus-wf**
@markerickson-wf @tannermiller-wf @johnlockwood-wf @tomdeering-wf

Permit prefixing import paths with a certain string to support devs who will place the generated code below the top level of their python hierarchy.

### CODE REVIEW

**Comment by tomdeering-wf** [comment]
Looks good. Is there some place to add tests?

**Comment by johnlockwood-wf** [comment]
Does it pass built in tests?

**Comment by ericklaus-wf** [comment]
It still passes built-in tests. There aren't any tests specifically testing generator output. Instead, there are unit tests and (extensive) integration tests verifying that servers can communicate with each other.

**Comment by tomdeering-wf** [comment]
> There aren't any tests specifically testing generator output.

That explains a lot :)

**Comment by ericklaus-wf** [comment]
@johnlockwood-wf @tomdeering-wf I'd rather not create a new unit test suite for this. How do you feel about this as-is?

**Comment by tomdeering-wf** [comment]
+1

**Comment by tannermiller-wf** [comment]
+1

**Comment by ericklaus-wf** [comment]
This was merged to Thrift master.

**Pull request closed without merging**
